language: node_js
node_js:
 - "12.10"

cache: npm

# Set permissions
before_script:
  - chmod +x ./scripts/build.sh

# Run build script
script: ./scripts/build.sh

# Deploy only from `vue-version` branch
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_TOKEN
  keep_history: true
  local_dir: dist
  target_branch: master
  on:
    branch: vue-version