language: node_js
node_js:
 - "node"

cache: npm

before_script:
  - chmod +x ./scripts/build.sh

script: ./scripts/build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_TOKEN
  keep_history: true
  local_dir: dist
  target_branch: master
  on:
    branch: vue-version